/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as CrashRouteImport } from './routes/crash'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TodosIndexRouteImport } from './routes/todos/index'
import { Route as TodosCreateNewTodoRouteImport } from './routes/todos/createNewTodo'
import { Route as TodosIdRouteImport } from './routes/todos/$id'

const CrashRoute = CrashRouteImport.update({
  id: '/crash',
  path: '/crash',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TodosIndexRoute = TodosIndexRouteImport.update({
  id: '/todos/',
  path: '/todos/',
  getParentRoute: () => rootRouteImport,
} as any)
const TodosCreateNewTodoRoute = TodosCreateNewTodoRouteImport.update({
  id: '/todos/createNewTodo',
  path: '/todos/createNewTodo',
  getParentRoute: () => rootRouteImport,
} as any)
const TodosIdRoute = TodosIdRouteImport.update({
  id: '/todos/$id',
  path: '/todos/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/crash': typeof CrashRoute
  '/todos/$id': typeof TodosIdRoute
  '/todos/createNewTodo': typeof TodosCreateNewTodoRoute
  '/todos': typeof TodosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/crash': typeof CrashRoute
  '/todos/$id': typeof TodosIdRoute
  '/todos/createNewTodo': typeof TodosCreateNewTodoRoute
  '/todos': typeof TodosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/crash': typeof CrashRoute
  '/todos/$id': typeof TodosIdRoute
  '/todos/createNewTodo': typeof TodosCreateNewTodoRoute
  '/todos/': typeof TodosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/crash' | '/todos/$id' | '/todos/createNewTodo' | '/todos'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/crash' | '/todos/$id' | '/todos/createNewTodo' | '/todos'
  id:
    | '__root__'
    | '/'
    | '/crash'
    | '/todos/$id'
    | '/todos/createNewTodo'
    | '/todos/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CrashRoute: typeof CrashRoute
  TodosIdRoute: typeof TodosIdRoute
  TodosCreateNewTodoRoute: typeof TodosCreateNewTodoRoute
  TodosIndexRoute: typeof TodosIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/crash': {
      id: '/crash'
      path: '/crash'
      fullPath: '/crash'
      preLoaderRoute: typeof CrashRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/todos/': {
      id: '/todos/'
      path: '/todos'
      fullPath: '/todos'
      preLoaderRoute: typeof TodosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/todos/createNewTodo': {
      id: '/todos/createNewTodo'
      path: '/todos/createNewTodo'
      fullPath: '/todos/createNewTodo'
      preLoaderRoute: typeof TodosCreateNewTodoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/todos/$id': {
      id: '/todos/$id'
      path: '/todos/$id'
      fullPath: '/todos/$id'
      preLoaderRoute: typeof TodosIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CrashRoute: CrashRoute,
  TodosIdRoute: TodosIdRoute,
  TodosCreateNewTodoRoute: TodosCreateNewTodoRoute,
  TodosIndexRoute: TodosIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
